### ISSUE TITLE
Display companies backing contributors

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/TopContributors#113]
Allow to switch the ranking so that it displays either individuals or organizations ("sponsors").

Contributions (PRs) are assigned to organizations following these rules:

* For each Pull Request, read the "sponsor company" in the PR's body.
* If the information is provided, the contribution counts toward that organization
* Else, try to match the PR author's GitHub username with a list of the usernames & known sponsor during the PR's creation timeframe (read below for more details)
* Else, try to fetch the author's company from their GitHub profile
* Else, mark that contribution as "individual" and exclude it from the ranking

### File examples

`known-sponsors.yml`

```yaml
PululuK:
  - from: 2016-09-01
    to: 2017-08-31
    sponsor: "Add One"
  - from: 2017-09-01
    to: 2021-10-01
    sponsor: "L'Agence 123"
  - from: 2022-07-01
    to:
    sponsor: "Evolutive Group"

eternoendless:
  - from: 2017-05-01
    to:
    sponsor: "PrestaShop SA"
```

`sponsors.yml`

```yaml
"PrestaShop SA":
  - github: "https://github.com/PrestaShopCorp/"
  - url: "https://www.prestashop.com/"
  - aliases: ["PrestaShop", "PrestaShopSA", "PrestaShopCorp"]

"Evolutive Group":
  - aliases: ["EvolutiveGroup"]
```
